### ISSUE TITLE
Workflow fails with waiting for selector "#badge-card-settings"

### ISSUE THREAD

**Issue by hariks789** [connorads/stackoverflow-fanatic#24]
A minor issue as progress is not halted only capturing progress stats screenshot fails

<img width="738" alt="Screenshot 2021-12-08 at 3 44 08 PM" src="https://user-images.githubusercontent.com/22391855/145190755-865903f3-b1ce-4519-85ff-7850ed984739.png">

**Comment by connorads** [comment]
Thanks @hariks789 should be fixed in #33
