### ISSUE TITLE
Prevent scheduled workflow from being disabled after 60 days

### ISSUE THREAD

**Issue by connorads** [connorads/stackoverflow-fanatic#3]
Need to prevent the scheduled workflow from being [disabled automatically after 60 days of repository inactivity](https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow).

> Warning: To prevent unnecessary workflow runs, scheduled workflows may be disabled automatically. When a public repository is forked, scheduled workflows are disabled by default. In a public repository, scheduled workflows are automatically disabled when no repository activity has occurred in 60 days.

1. Create a workflow to do periodic git commits?
2. Or, use existing workflow but do repo activity at 30/60/90 days once badge progress can be tracked in #2?

Update: Since #4 has failed. We can take advantage of the 60 day inactivity cutoff to disable the workflow.
Perhaps run this git activity thing at 42/100 days? https://github.com/steveukx/git-js

**Comment by lgmorand** [comment]
@connorads finally, what did you use as workaround to "prevent" the auto disabling and simulate activity ?

**Comment by connorads** [comment]
Hey @lgmorand,

The `42` is here
https://github.com/connorads/stackoverflow-fanatic/blob/00ef1b9b6afb2f443ba7d50c4391e341ab19ebe9/src/index.ts#L69

However, unfortunately I believe my workaround(s) never worked and I must not have updated the readme 😞 
Think I just had to click a button in the email to stop it from being disabled, or something like that.

**Comment by lgmorand** [comment]
haha thanks. just found this gem. I'll give a try
https://github.com/marketplace/actions/keepalive-workflow
