### ISSUE TITLE
Workflow fails (timeout) just after login during "go to profile"

### ISSUE THREAD

**Issue by beuted** [connorads/stackoverflow-fanatic#32]
![image](https://user-images.githubusercontent.com/2879233/210217885-9954c140-a558-4db1-ad68-eacb51a59318.png)

What I've tried:

* I've triple checked that my password and emails are the right ones
* I've hardcoded emaila nd password in the script instead of using env variables

I'm new to playright maybe there is a way to debug this easily ?

**Comment by connorads** [comment]
Salut @beuted,

It's been a while since I've looked at this so it could be broken 🤷‍♂️ 

Have you tried running it in non-headless mode?
This lets you see the browser as it's clicking around etc.
`const browser = await playwright['chromium'].launch({ headless: false });`

https://playwright.dev/docs/library#first-script

**Comment by beuted** [comment]
Nah I think the issue is that some of the elements class and id have changed since you implemented it.
(Even the tests of the repo are broken I think)
I'll try to fix it on my side and send a PR on your repo if I manage to fix it :)

**Comment by beuted** [comment]
I've created this PR https://github.com/connorads/stackoverflow-fanatic/pull/33

**Comment by beuted** [comment]
And this one to be merged first to fix the tests: https://github.com/connorads/stackoverflow-fanatic/pull/34

**Comment by connorads** [comment]
Merci beaucoup monsieur 🙏 Merged both the PRs.
Is it all working now?

Bear in mind that the Readme currently lies a bit https://github.com/connorads/stackoverflow-fanatic/issues/15#issuecomment-915559163 👀

**Comment by beuted** [comment]
A manual run worked so I think it should be good.
I'll check tomorrow if it has run in the night :)

**Comment by connorads** [comment]
Hey @beuted, I'm guessing it is working now and can close this? 👀

**Comment by beuted** [comment]
Yeap thanks
