### ISSUE TITLE
Hitting Cloudflare Captcha in GitHub Actions

### ISSUE THREAD

**Issue by connorads** [connorads/stackoverflow-fanatic#44]
Guess this might not work anymore 🥲 #43
![image](https://github.com/connorads/stackoverflow-fanatic/assets/10026538/c880920d-7d62-4d59-8f4e-3797e94a3e7d)

**Comment by sigtrygg-space** [comment]
seems to be working again... Maybe those captchas don't show up any more?

**Comment by connorads** [comment]
> seems to be working again... Maybe those captchas don't show up any more?

Nice one, yes looks that way!
